{
 "title": "Symfony app metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "App requests total",
   "type": "graph",
   "description": "Requests executed in Symfony application per router.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_request_called_quantity_total) by (router)",
     "legendFormat": "{{ router }}"
    }
   ]
  },
  {
   "title": "App request execution time",
   "type": "graph",
   "description": "Requests execution time in Symfony application per request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_request_execution_time_seconds_sum) by (router)/sum(app_request_execution_time_seconds_count) by (router)",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "App request db query total",
   "type": "graph",
   "description": "Db queries executed in Symfony application per router.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_request_db_query_quantity_sum) by (router) / sum(app_request_db_query_quantity_count) by (router)",
     "legendFormat": "{{ router }}"
    }
   ]
  },
  {
   "title": "App request db query execution time",
   "type": "graph",
   "description": "Database execution time in Symfony application per request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_request_db_query_execution_time_seconds_sum) by (router) / sum(app_request_db_query_execution_time_seconds_count) by (router)",
     "legendFormat": "{{ router }} "
    }
   ]
  },
  {
   "title": "DB query type summary",
   "type": "graph",
   "description": "Summary of database query execution per type, routing, and table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_request_db_query_type_sum) by (type, router, table_name)",
     "legendFormat": "{{router}} {{type}} {{table_name}}"
    }
   ]
  }
 ]
}